[LinkedIn]
domain = "linkedin.com"

[Twitter]
domain = "twitter.com"

[YouTube]
domain = "youtube.com"

[Facebook]
domain = "facebook.com"

[Instagram]
domain = "instagram.com"

[Glassdoor]
domain = "glassdoor.com"

[Crunchbase]
domain = "crunchbase.com"

[Github]
domain = "github.com"
